// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validação das variáveis de ambiente
const EXPECTED_URL = 'https://hkqrgomafbohittsdnea.supabase.co';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMessage = `
╔════════════════════════════════════════════════════════════════╗
║  ERRO: Variáveis de ambiente do Supabase não configuradas!    ║
╚════════════════════════════════════════════════════════════════╝

Por favor, crie o arquivo .env.local na raiz do projeto com:

VITE_SUPABASE_URL=https://hkqrgomafbohittsdnea.supabase.co
VITE_SUPABASE_PUBLISHABLE_KEY=sb_publishable_Q7QBDFMNFtzZw9b3xfZJJQ_7SeUE7-q

Depois:
1. Reinicie o servidor de desenvolvimento
2. Limpe o cache do navegador
3. Faça logout e login novamente

Veja CONFIGURACAO_SUPABASE.md para mais detalhes.
  `;
  console.error(errorMessage);
  throw new Error('Variáveis de ambiente do Supabase não configuradas. Veja o console para mais detalhes.');
}

if (SUPABASE_URL !== EXPECTED_URL) {
  console.warn(`
╔════════════════════════════════════════════════════════════════╗
║  AVISO: URL do Supabase não corresponde ao projeto correto!  ║
╚════════════════════════════════════════════════════════════════╝

URL atual: ${SUPABASE_URL}
URL esperada: ${EXPECTED_URL}

O projeto deve usar APENAS o Supabase de backend (hkqrgomafbohittsdnea).
Verifique o arquivo .env.local e reinicie o servidor.
  `);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
